language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: sm+DPm8RpuEWdykNqqpt3j2Y3vPtqrkOF5NKndtOuDPCplyv8Kbic4M70GqYLXmu5OUWj0L88zj5OQw7bd5stVT1drwbRtKYlXEJO8B3e3kkcx/2dsGl++B6fkiHbggVvlaDazX0QWRrBpF+fSoRmreph7x2SOcSsh9I5U93MUMPlM8RZMasNXAVmctuxxrW3Wvu4OcWPiOMudihHxcKMJ7oJnE5DZUNsMwZJd1rVKovQFqiV7ivIeXtvRGEUM+9FFZ05l2sDOnQShaS6GFJD0thhdhPAPHkYJPqfa5XXKTzz9B3lK+Jps4x3+cOIHVl2pOrn+EfVbDAS23wHZozptcUsvsCE+28GurSegZZBOvcAd/TFhj0m0BY68hlYgbHKGGAL7CxgOZBUA4bb/a4//5WxCc9uHdlrnDTIUcVA0g3JuMcfiWVl/Mu72zFunormyMBR9C5xUApGKHXobT/xdomnNtL7zEX9PW8BW4tINrFXUfEW0cvZT22o7AZcKSmH9bFJmbDm6nNckfT2yMRTqgaG/oZJ0Y8FV7SJAVmi7LNOLTm0cHG6J0NXFfJ+Zj+DnPRH5BMGvKJIDjuIl+vH0MPSJOkqeHe8ZIc+RXW3SicRhOphDYqa/HYV/g2/oH7/O1p00Y+Ob4oCLC/fRBGQHjnOeufj4zxlAwJdl1SCf0=
  app: obscure-crag-69391
  on:
    repo: calysabean/Blog-post-update
