language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: eead5be4-6b69-4a42-b5e2-19103eb8aaa1
  app: obscure-crag-69391
  on:
    repo: calysabean/Blog-post-update
